### ISSUE TITLE
marked 解析不全 mavonEditor 保存的文本

### ISSUE THREAD

**Issue by YoySun** [miqilin21/vue-blog#12]
marked 为何解析不了mavonEditor 配置的左右边距列表等等类似word的操作

**Comment by zonemeen** [comment]
> 

有图吗 贴一张来看看

**Comment by zonemeen** [comment]
> marked 为何解析不了mavonEditor 配置的左右边距列表等等类似word的操作
你好 有图吗 贴一张我看看

**Comment by zonemeen** [comment]
> marked 为何解析不了mavonEditor 配置的左右边距列表等等类似word的操作

你好 贴一张图片什么的 我看看

**Comment by YoySun** [comment]
> 

![image](https://user-images.githubusercontent.com/40062515/157785074-cb6b3979-4344-4acb-8ba1-44f7d7f1028d.png)
![image](https://user-images.githubusercontent.com/40062515/157785178-99f5fe7d-6b4b-4bc4-bfa5-267ec59700bc.png)
类似这样子，博客前台页面marked 未能正确解析

**Comment by chenmaolan** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/40062515/157785074-cb6b3979-4344-4acb-8ba1-44f7d7f1028d.png) ![image](https://user-images.githubusercontent.com/40062515/157785178-99f5fe7d-6b4b-4bc4-bfa5-267ec59700bc.png) 类似这样子，博客前台页面marked 未能正确解析

**Comment by YoySun** [comment]
> > marked 为何解析不了mavonEditor 配置的左右边距列表等等类似word的操作
> 
> 你好 贴一张图片什么的 我看看

highlight高亮失效 你这边是否可以呢？

**Comment by YoySun** [comment]
解决了，是因为mavon-editor 使用的特殊高亮字符，marked 是不生效的，所以在web端下载了mavon-editor 组件，并调用getMarkdownIt 方法，就能正确解析对应样式
![image](https://user-images.githubusercontent.com/40062515/157855473-c3816660-77e1-47e6-8966-4acb54f26b75.png)
